name: Test

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install dash plotly pandas
      - name: Run app
        run: |
          python app.py
      - name: Wait for app to start
        run: |
          sleep 10
      - name: Test app
        run: |
          curl http://127.0.0.1:8050/

      # Add more steps as needed
