name: Test

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install dash[testing] plotly pandas
      - name: Run app
        run: |
          pytest


      # Add more steps as needed
